const TOGGLESIDE = 'TOGGLESIDE';//sidebar是否进入
const FETCHLIST = 'FETCHLIST';//获取投资列表

//
const FETCH_INVESTLIST = 'FETCH_INVESTLIST';
const RECEIVE_INVESTLIST = 'RECEIVE_INVESTLIST'

const LOGINING = 'LOGINING';
const LOGINED = 'LOGINED'


const LOGINOUT = 'LOGINOUT'




export { TOGGLESIDE, FETCHLIST, FETCH_INVESTLIST, RECEIVE_INVESTLIST, LOGINING, LOGINED, LOGINOUT }